program : main.o
        gcc -g -O0 -o program main.o
main.o : main.c
        gcc -c -std=c89 -pedantic-errors -g -O0 -Wall -Wextra main.c
clean :
        rm *.o
new :
        rm program
rmback :
        rm *~
